# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/oplus/sm8350-common/setup-makefiles.sh

LOCAL_PATH := $(call my-dir)

ifneq ($(filter lemonade lemonadep RMX2202 RMX3360,$(TARGET_DEVICE)),)

endif
